// Mock product data for demonstration
export const mockProducts = [
  {
    id: "1",
    name: "Silk Midi Dress",
    price: 299,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80",
    category: "Dresses",
    isNew: true,
    description: "Elegant silk midi dress with a flattering silhouette",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Blush", "Ivory", "Navy"],
  },
  {
    id: "2",
    name: "Leather Crossbody Bag",
    price: 189,
    image: "https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&q=80",
    category: "Accessories",
    isNew: false,
    description: "Premium leather crossbody bag with gold hardware",
    colors: ["Black", "Tan", "Rose"],
  },
  {
    id: "3",
    name: "Pointed Toe Heels",
    price: 159,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80",
    category: "Shoes",
    isNew: true,
    description: "Classic pointed toe heels in premium leather",
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["Nude", "Black", "Rose Gold"],
  },
  {
    id: "4",
    name: "Pearl Drop Earrings",
    price: 129,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
    category: "Jewelry",
    isNew: false,
    description: "Elegant pearl drop earrings with gold accents",
    colors: ["Gold", "Silver"],
  },
  {
    id: "5",
    name: "Cashmere Sweater",
    price: 249,
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80",
    category: "Knitwear",
    isNew: true,
    description: "Luxurious cashmere sweater with ribbed detailing",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Blush", "Camel"],
  },
  {
    id: "6",
    name: "Satin Clutch",
    price: 89,
    image: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800&q=80",
    category: "Accessories",
    isNew: false,
    description: "Elegant satin clutch perfect for evening wear",
    colors: ["Champagne", "Navy", "Black"],
  },
  {
    id: "7",
    name: "Linen Maxi Dress",
    price: 279,
    image: "https://images.unsplash.com/photo-1572804013427-4d7ca7268217?w=800&q=80",
    category: "Dresses",
    isNew: true,
    description: "Flowing linen maxi dress with adjustable straps",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Sage", "Terracotta"],
  },
  {
    id: "8",
    name: "Gold Chain Necklace",
    price: 149,
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80",
    category: "Jewelry",
    isNew: false,
    description: "Delicate gold chain necklace with pendant",
    colors: ["Gold", "Rose Gold"],
  },
];

export const categories = [
  {
    title: "Dresses",
    link: "/shop?category=dresses",
  },
  {
    title: "Accessories",
    link: "/shop?category=accessories",
  },
  {
    title: "Shoes",
    link: "/shop?category=shoes",
  },
  {
    title: "Jewelry",
    link: "/shop?category=jewelry",
  },
];
